-- Student Marks Management System
-- Run as STUDENT_APP after connecting to FREEPDB1.

-- Drop in dependency order if you want a clean rebuild.
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MARKS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CURRICULUM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUBJECT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DEPARTMENT (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_code VARCHAR2(20) NOT NULL,
    department_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id),
    CONSTRAINT uk_department_code UNIQUE (department_code)
);

CREATE TABLE STUDENT (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    roll_no VARCHAR2(20) NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50),
    department_id NUMBER NOT NULL,
    current_semester NUMBER(2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_student PRIMARY KEY (student_id),
    CONSTRAINT uk_student_roll UNIQUE (roll_no),
    CONSTRAINT chk_student_semester CHECK (current_semester BETWEEN 1 AND 8),
    CONSTRAINT fk_student_department FOREIGN KEY (department_id)
        REFERENCES DEPARTMENT(department_id)
);

CREATE TABLE SUBJECT (
    subject_code VARCHAR2(20) NOT NULL,
    subject_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_subject PRIMARY KEY (subject_code),
    CONSTRAINT uk_subject_name UNIQUE (subject_name)
);

CREATE TABLE CURRICULUM (
    department_id NUMBER NOT NULL,
    semester NUMBER(2) NOT NULL,
    subject_code VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_curriculum PRIMARY KEY (department_id, semester, subject_code),
    CONSTRAINT fk_curriculum_department FOREIGN KEY (department_id)
        REFERENCES DEPARTMENT(department_id),
    CONSTRAINT fk_curriculum_subject FOREIGN KEY (subject_code)
        REFERENCES SUBJECT(subject_code),
    CONSTRAINT chk_curriculum_semester CHECK (semester BETWEEN 1 AND 8)
);

CREATE TABLE MARKS (
    student_id NUMBER NOT NULL,
    subject_code VARCHAR2(20) NOT NULL,
    score NUMBER(5,2) NOT NULL,
    grade VARCHAR2(2),
    CONSTRAINT pk_marks PRIMARY KEY (student_id, subject_code),
    CONSTRAINT fk_marks_student FOREIGN KEY (student_id)
        REFERENCES STUDENT(student_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_marks_subject FOREIGN KEY (subject_code)
        REFERENCES SUBJECT(subject_code),
    CONSTRAINT chk_marks_score CHECK (score BETWEEN 0 AND 100)
);

COMMIT;
