-- Student Marks Management System master/reference data
-- Department IDs intentionally match the current application data: 1=CS, 2=AIDS.
INSERT INTO DEPARTMENT (department_id, department_code, department_name) VALUES (1, 'CS', 'Computer Science');
INSERT INTO DEPARTMENT (department_id, department_code, department_name) VALUES (2, 'AIDS', 'Artificial Intelligence and Data Science');

-- Subject master data.
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS101', 'Programming Fundamentals');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS102', 'Engineering Mathematics I');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS103', 'Digital Logic');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS104', 'Computer Organization');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS105', 'Communication Skills');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS201', 'Data Structures');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS202', 'Engineering Mathematics II');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS203', 'Database Management Systems');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS204', 'Object Oriented Programming');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS205', 'Operating Systems');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS301', 'Computer Networks');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS302', 'Software Engineering');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS303', 'Web Technology');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS304', 'Statistics and Probability');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS305', 'Artificial Intelligence');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS306', 'Design and Analysis of Algorithms');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS307', 'Theory of Computation');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS401', 'Machine Learning');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS402', 'Compiler Design');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS403', 'Cloud Computing');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS404', 'Cyber Security');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS405', 'Distributed Systems');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS406', 'Data Science');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS407', 'Big Data Analytics');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS501', 'Advanced Java');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS502', 'Advanced Database Systems');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS503', 'Deep Learning');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS504', 'Data Mining');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS505', 'Natural Language Processing');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS506', 'Data Visualization');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS507', 'Generative AI');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS601', 'Internet of Things');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS602', 'Blockchain Technology');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS603', 'DevOps');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS604', 'Mobile Computing');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS605', 'Information Retrieval');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS606', 'Computer Vision');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS607', 'Reinforcement Learning');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS701', 'Project Management');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS702', 'Software Testing');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS703', 'UI/UX Design');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS704', 'Business Intelligence');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS705', 'Edge Computing');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS706', 'MLOps');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS801', 'Project Work');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS802', 'Seminar');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS803', 'Internship');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS804', 'Professional Ethics');
INSERT INTO SUBJECT (subject_code, subject_name) VALUES ('CS805', 'Capstone Project');

-- Curriculum: exactly 5 subjects for every department/semester combination.
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 1, 'CS101');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 1, 'CS102');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 1, 'CS104');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 1, 'CS105');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 1, 'CS103');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 2, 'CS201');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 2, 'CS202');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 2, 'CS203');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 2, 'CS204');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 2, 'CS205');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 3, 'CS301');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 3, 'CS302');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 3, 'CS303');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 3, 'CS306');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 3, 'CS307');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 4, 'CS401');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 4, 'CS402');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 4, 'CS403');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 4, 'CS404');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 4, 'CS405');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 5, 'CS501');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 5, 'CS502');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 5, 'CS503');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 5, 'CS504');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 5, 'CS505');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 6, 'CS601');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 6, 'CS602');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 6, 'CS603');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 6, 'CS604');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 6, 'CS605');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 7, 'CS701');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 7, 'CS702');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 7, 'CS703');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 7, 'CS704');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 7, 'CS705');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 8, 'CS801');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 8, 'CS802');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 8, 'CS803');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 8, 'CS804');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (1, 8, 'CS805');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 1, 'CS101');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 1, 'CS102');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 1, 'CS104');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 1, 'CS305');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 1, 'CS304');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 2, 'CS201');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 2, 'CS202');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 2, 'CS203');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 2, 'CS305');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 2, 'CS406');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 3, 'CS301');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 3, 'CS302');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 3, 'CS307');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 3, 'CS304');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 3, 'CS305');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 4, 'CS401');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 4, 'CS402');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 4, 'CS403');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 4, 'CS406');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 4, 'CS407');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 5, 'CS503');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 5, 'CS504');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 5, 'CS506');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 5, 'CS507');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 5, 'CS305');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 6, 'CS601');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 6, 'CS602');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 6, 'CS606');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 6, 'CS607');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 6, 'CS506');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 7, 'CS701');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 7, 'CS704');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 7, 'CS705');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 7, 'CS706');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 7, 'CS507');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 8, 'CS801');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 8, 'CS803');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 8, 'CS804');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 8, 'CS606');
INSERT INTO CURRICULUM (department_id, semester, subject_code) VALUES (2, 8, 'CS607');

COMMIT;